Hydrogen Gas Turbines and Retrofitting of Gas Turbines
PyPSA/pypsa-ariadne pull request #151
Opened 2024-08-02 12:11 UTC by toniseibold

Adding the following configs
```
electricity:
  H2_plants_DE:
    enable: true
    retrofit_CH4_to_H2:
      enable: true
      efficiency_loss: 0.1
      cost_increase: 0.1
      start: 2025
      force: 2035
```

### modify_prenetwork
- if `config["H2_plants_DE"]["enable"] the extendable links for OCGT, CCGT and gas CHPs in the current planning horizon are copied and added so hydrogen turbines can be built as well
- if the retrofitting of existing OCGT, CCGT, gas CHPs in enabled, existing gas plant links are copied and added as retrofitted H2 links (boundary condition is set in additional functionality) from `config["start"]`on
- if the `config["force"] is set, from the force year on, all OCGT, CCGT, gas CHPs links from `config["start"] on are dropped and only the hydrogen links exist

### additional_functionality
- in case that `config["retrofit_CH4_to_H2"]["enable"]` is set, gas plant links and hydrogen retro links are added as a boundary condition in a way, that the installed capacity of both must be lower equal than the former installed capacity of gas plants

Open issues:
- [ ] check the efficiency decrease
- [ ] check the costs for retrofitting

2024-08-02 12:35 UTC, nworbmot commented on workflow/scripts/additional_functionality.py
> +    if params["start"] <= year:
this should be elif?

2024-08-06 06:40 UTC, toniseibold commented
Model results for 3H resolution KN2045_Bal_v4 scenario:
![image](https://github.com/user-attachments/assets/d278be75-8155-4650-87cb-fd43da5b6b41)
Open Cycle capacity agrees with the latest [model run](https://tubcloud.tu-berlin.de/apps/files/?dir=/Shared/ensys_intern/Projekte/2023-Ariadne2/run_results/20240712industrysteam&fileid=4046145748) but model is now also favoring H2 gas turbines:
![image](https://github.com/user-attachments/assets/9f36b702-bfde-482a-a67b-5a1c59fa47a7)

2024-08-08 13:49 UTC, lindnemi requested changes
looking very good, just two minor style suggestions then it can be merged

2024-08-08 13:49 UTC, lindnemi commented on workflow/scripts/modify_prenetwork.py
> +        h2_plants.efficiency2 = 1  # default value
it's a bit strange that the default value is 0 for H2 plants, but 1 for H2 retro plants

2024-08-08 13:49 UTC, lindnemi commented on config/config.yaml
> +    urban central H2 retro CHP: '#ff0000'
i would prefer if they are called `H2 retrofit` instead of `H2 retro`

2024-08-08 14:00 UTC, lindnemi commented
I just noticed that there are several more variables in the exporter that need to be adjusted, e.g. capacity|hydrogen and secondary energy input. basically all lines which have "H2 Fuel Cell" in master

2024-08-08 15:51 UTC, lindnemi commented
i updated the exporter

however, the workflow is still failing because of a bug in `make_summary`. We should figure that out before merging :thinking:

2024-08-09 09:22 UTC, lindnemi commented
plot_summary was failing because the H2 plants were connected to a non-existent `DE H2` bus, and the retrotfitted ones to an equally non existent `DE H2 retro` bus. I corrected these to the spatially resolved `DE1 X H2` buses.

I really wonder why the optimization went through at all and did not brake. @nworbmot @toniseibold 

In the 365H resolution no gas or H2 turbines get built. If this stays the same for 3H we will have to force in the Kraftwerkstrategie plants:

![Capacity-Additions-Electricity-Gas](https://github.com/user-attachments/assets/827a1b70-97b2-4f50-9afa-e15f834ebad3)

![Capacity-Additions-Electricity-Hydrogen](https://github.com/user-attachments/assets/1b338a6b-764c-4aae-bc3a-0ed83cb1edc9)


The hydrogen capacity is all fuel cells at the moment.


However, we do see gas boilers being built. Maybe those should be retrofittable to H2 as well?
![Capacity-Additions-Heat-Gas](https://github.com/user-attachments/assets/0ec59819-9550-487f-be38-ca73d2f52a95)

2024-08-09 10:08 UTC, merged