Adding capacity limit for MeOH and FT
PyPSA/pypsa-ariadne pull request #272
Opened 2024-11-05 14:26 UTC by toniseibold

Closing https://github.com/PyPSA/pypsa-ariadne/issues/271

Before asking for a review for this PR make sure to complete the following checklist:

- [ ] Workflow with target rule `ariadne_all` completes without errors
- [ ] The logic of `export_ariadne_variables` has been adapted to the changes
- [ ] One or several figures that validate the changes in the PR have been posted as a comment
- [ ] A brief description of the changes has been added to `Changelog.md`
- [ ] The latest `main` has been merged into the PR
- [ ] The config has a new prefix of the format `YYYYMMDDdescriptive_title`

2024-11-06 09:15 UTC, lindnemi requested changes

2024-11-06 09:15 UTC, lindnemi commented on config/config.yaml
> +      Link:
This  should be a limit_capacity_max, not _min

2024-11-06 09:15 UTC, lindnemi commented on workflow/scripts/additional_functionality.py
> +                    c.df.loc[existing_index, "efficiency"].mean()
No need to use `mean`, better multiply the vectors. 

[For FT there should be no problems, but this function is more general and e.g. for gas turbines there would be a difference]

2024-11-06 09:15 UTC, lindnemi commented on workflow/scripts/additional_functionality.py
> +                    c.df.loc[existing_index, attr + "_nom"].sum() / efficiency
i think the efficiency has to be multiplied, not divided

2024-11-06 09:15 UTC, lindnemi commented on workflow/scripts/additional_functionality.py
> +                lhs = nom.sum() / efficiency
again, i think `*` instead of `/`

2024-11-06 09:15 UTC, lindnemi commented on workflow/scripts/additional_functionality.py
> +        ).sum() / efficiency
lines 241 and 245, same as above

2024-11-06 15:08 UTC, toniseibold commented
Bug: Constraint active (e.g. in 2035 mu != 0) but capacities not built to the maximum

2024-11-07 15:48 UTC, JulianGeis commented
the constraint seem to be fine:
![image](https://github.com/user-attachments/assets/cc5a3bf9-d26a-42ae-9156-3f669d1a9c35)

However, there is something going wrong in the optimisation. TBC

2024-11-12 11:08 UTC, lindnemi commented
superseded by #278 and some direct commits to main

2024-11-12 11:08 UTC, closed without merging